DATA_SHEET = 'Measured Data'
FEED_SHEET = 'Feed'
SEPARATE_FEED_SHEET = 'Separate Feed Data'

EXPERIMENT_DATA_COLUMN = 'Experiment Data'
CONC_BEFOROE_FEED_COLUMN = 'Concentration Before Feeding'
CONC_AFTER_FEED_COLUMN = 'Concentration After Feeding'
MEASURED_CUMULATIVE_COLUMN = 'Calculated Cumulative Concentration'

DATE_COLUMN = 'Date (MM/DD/YY H:MM:SS AM/PM)'
CELL_LINE_COLUMN = 'Cell Line'
ID_COLUMN = 'ID' 
NAME_COLUMN = 'Name'
INITIAL_VOLUME_COLUMN = 'Initial Volume (mL)'
SAMPLE_VOLUME_COLUMN = 'Sample Volume (mL)'
VOLUME_BEFORE_SAMPLE_COLUMN = 'Volume Before Sampling (mL)'
VOLUME_AFTER_SAMPLE_COLUMN = 'Volume After Sampling (mL)'
FEED_MEDIA_ADDED_COLUMN = 'Feed Media Added (mL)'
BASE_ADDED_COLUMN = 'Base Added (mL)'
VIABLE_CELL_COLUMN = 'Viable Cell Concentration (10^6 cells/mL)'
DEAD_CELL_COLUMN = 'Dead Cell Concentration (10^6 cells/mL)'
TOTAL_CELL_COLUMN = 'Total Cell Concentration (10^6 cells/mL)'
PRODUCT_COLUMN = 'IgG (mg/L)'

RUN_TIME_DAY_COLUMN = 'Run Time (day)'
RUN_TIME_HOUR_COLUMN = 'Run Time (hr)'
RUN_TIME_DAY_MID_COLUMN = 'Run Time Mid (day)'
RUN_TIME_HOUR_MID_COLUMN = 'Run Time Mid (hr)'