SPECIES_LIST = [
    'Alanine',
    'Ammonia',
    'Arginine',
    'Asparagine',
    'Aspartate',
    'Cystine',
    'Glucose',
    'Glutamine',
    'Glutamate',
    'Glycine',
    'Histidine',
    'Isoleucine',
    'Lactate',
    'Leucine',
    'Lysine',
    'Methionine',
    'Nh3',
    'Phenylalanine',
    'Proline',
    'Serine',
    'Threonine',
    'Tryptophan',
    'Tyrosine',
    'Valine',
    'Ethanolamine',
    ]

SPECIES_ABBR = {
    'Alanine'       : 'ALA', 
    'Ammonia'       : 'NH3',
    'Arginine'      : 'ARG', 
    'Asparagine'    : 'ASN',
    'Aspartate'     : 'ASP', 
    'Cystine'       : 'CYS', 
    'Glucose'       : 'GLC',
    'Glutamine'     : 'GLN', 
    'Glutamate'     : 'GLU', 
    'Glycine'       : 'GLY',
    'Histidine'     : 'HIS', 
    'Isoleucine'    : 'ILE',
    'Lactate'       : 'LAC',
    'Leucine'       : 'LEU', 
    'Lysine'        : 'LYS', 
    'Methionine'    : 'MET',
    'Nh3'           : 'NH3',
    'Phenylalanine' : 'PHE', 
    'Proline'       : 'PRO',
    'Serine'        : 'SER', 
    'Threonine'     : 'THR', 
    'Tryptophan'    : 'TRP',
    'Tyrosine'      : 'TYR', 
    'Valine'        : 'VAL', 
    'Ethanolamine'  : 'ETN',
    }

SPECIES_STATE = {
    'IgG'           : 'Produced',
    'Alanine'       : 'Consumed', 
    'Ammonia'       : 'Produced',
    'Arginine'      : 'Consumed', 
    'Asparagine'    : 'Consumed',
    'Aspartate'     : 'Consumed', 
    'Cystine'       : 'Consumed', 
    'Glucose'       : 'Consumed',
    'Glutamine'     : 'Consumed', 
    'Glutamate'     : 'Consumed', 
    'Glycine'       : 'Consumed',
    'Histidine'     : 'Consumed', 
    'Isoleucine'    : 'Consumed',
    'Lactate'       : 'Produced',
    'Leucine'       : 'Consumed', 
    'Lysine'        : 'Consumed', 
    'Methionine'    : 'Consumed',
    'Nh3'           : 'Produced',
    'Phenylalanine' : 'Consumed', 
    'Proline'       : 'Consumed',
    'Serine'        : 'Consumed', 
    'Threonine'     : 'Consumed', 
    'Tryptophan'    : 'Consumed',
    'Tyrosine'      : 'Consumed', 
    'Valine'        : 'Consumed', 
    'Ethanolamine'  : 'Consumed',
    }

SPECIES_MOLAR_MASS = {
    'Alanine'       :89.09,
    'Ammonia'       :17.03,
    'Arginine'      :174.2, 
    'Asparagine'    :132.12,
    'Aspartate'     :133.10, 
    'Cystine'       :240.30, 
    'Glucose'       :180.16,
    'Glutamate'     :147.13, 
    'Glutamine'     :146.15, 
    'Glycine'       :75.07,
    'Histidine'     :155.16, 
    'Isoleucine'    :131.18, 
    'Lactate'       :90.08,
    'Leucine'       :131.18, 
    'Lysine'        :146.19, 
    'Methionine'    :149.21, 
    'Nh3'           :17.03,
    'Phenylalanine' :165.19, 
    'Proline'       :115.13,
    'Serine'        :105.09, 
    'Threonine'     :119.12, 
    'Tryptophan'    :204.23,
    'Tyrosine'      :181.19,
    'Valine'        :117.15, 
    'Ethanolamine'  :61.08,
}